name: Deploy Django App with Tunnelmole

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the Python version of your choice

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django server
        run: |
          python manage.py runserver 0.0.0.0:8000 &
          sleep 10  # Wait for the server to start

      - name: Install Tunnelmole
        run: |
          curl -sSL https://tunnelmole.com/downloads/tunnelmole-linux-amd64.tar.gz | tar xz
          sudo mv tunnelmole /usr/local/bin/
          tunnelmole --version  # Verify installation

      - name: Start Tunnelmole
        run: |
          tunnelmole -port 8000 &
          sleep 10  # Wait for Tunnelmole to establish the tunnel

      - name: Run tests
        run: |
          python manage.py test
